# Topics under scrutiny

## Introduction

This section presents the main topics studied with the HIES 2019 for the SoMix project.

Our overarching research theme is:

***Who Benefits from Public Goods? Socio-spatial Inequalities in the Access and Use of Health and Education Services in Sri Lanka***

For the quantitative part of the project, we have already identified a number of topics that will drive our research project.

## General instructions

-   **Assemble in groups** of 4-5 students. Your group correspond to your university/institution and you will work collaboratively and create ***three*** deliverables together.

-   Choose **one** **topic per group** from the table below. Each group needs to have its own topic.

-   Carefully **read the information** provided in the below table regarding your chosen topic (database to use, corresponding section in the questionnaire).

## Deliverables for the Quant workshop

*Note: these deliverables are different from the Qual workshop. You need to complete all deliverables from the Quant and Qual workshops!*

### Analytical Plan (D1)

-   Start laying out an **analytical plan** for your study. This includes:

    -   Section 1: Identify references (5 to 10) and write a (small) **literature review** on your topic that will help you understand what is the current knowledge on your topic. Save your references in Zotero and use it to organize your document. It may help you identify loopholes in terms of what is not known regarding your topic.

    -   Section 2: It will help you shape your thinking in terms of **hypotheses** (2 to 3) that you will also write down.

    -   Section 3: write a small **method** section. Move back to the questionnaire and data. You need to identify the variables from the HIES that will be used to test your hypotheses.

        -   What is your **dependent variable**? (or your dependent variables if you think your topic covers multiple objects of investigation). You will need to refer to the HIES questionnaire section(s) covering your topic and select the relevant question, then identify the corresponding variables in the database. As a reminder, the HIES 2019 questionnaire is shown below.

        -   What are the main **independent variables** you want to study? Generally, these are socio-demographic variables. These variables should be of analytical interest, i.e. you should either have a sociological reasoning to include them (you know of some theory, previous literature, etc... suggesting that this variable may be linked to the dependent variable that you want to study), or you make the assumption that the variable is so central in shaping the Sri Lankan social landscape that it just cannot be left out. You can refer to the ***Introduction section*** to recall the main constructed socio-spatial variables in the data.

***=\> This is the FIRST deliverable for the Quant part during this year (Google Document in your assigned folder, 1.5 to 2 pages, Font: Arial, Size: 12, simple spacing).***

**=\> Due date: January 31, 2026.**

### Statistical Analysis (D3)

-   After receiving feedback from your trainers, prepare the **statistical analysis,** whichincludes:

    -   **Univariate statistics**: for all variables that you have listed above, run univariate statistics on your database. Be careful if these are numerical or categorical variables! Do not forget: e.g., missing observations should be carefully examined, frequencies (N) are unweighted but percentages are weighted... (see previous sections)

        -   If some variables require recoding tasks, justify and run them in your R script.

        -   Save the tables/graphics in a document (Google Doc).

    -   **Bivariate/multivariate analysis**

        -   Conduct **bivariate** or **multivariate** statistics. This may include mean/standard deviation by a categorical variable, cross tabulations, graphics...

        -   Identify the ***most relevant results*** of your statistical treatments (at this this step it should have at least 4 tables/figures and up to 6 tables/figures). Include the outputs in your Google Document.

        -   Write a couple of **analytical sentences** describing your statistical analyses for each tables/figures.

        -   **Save** your code (.R file) and your analysis (in a document)!

***=\> This is the SECOND deliverable for the Quant part during this year (one code file and one document containing all relevant analyses).***

**=\> Due date: March 31, 2026.**

### Draft report (D5)

-   After receiving feedback from your trainers, you can finally work on the final deliverable that pulls together everything you have done together. In a new Google Document, include:

    -   The edited **Analytical Plan** (i.e., you need to take into account our comments from the first deliverable).

    -   The modified **Statistical analysis** (statistical outputs + analytical sentences). You need to select the most important results among your statistical analyses (trainers will advise you for this) and to complete writing the analytical description of these results.

    -   Add a section for your final **Sociological interpration & Discussion** (1 page), which includes these elements:

        -   How do your own results (statistical outputs) **contradict** or **support** your reasoning before conducting these statistical analysis?

        -   What is new in your results that you did not know before, **confirms** or **contradicts** the sociological literature, etc?

        -   What could possibly be done in terms of **qualitative study** to push further these analyses?

    -   In this newly compiled document, add a short introduction, conclusion, and a bibliography with references.

    -   Once you have done all that, there is still a final step that is important: be sure to read everything from the beginning to ensure it makes sense and that all the parts fit together well!

***=\> This is the THIRD deliverable for the Quant part during this year (one code file and one document containing all relevant analyses).***

**=\> Due date: June 30, 2026.**

## A quick presentation of each topic

Below is a suggested list of available topics.

| Topic | Starting question | Database | Section of the HIES questionnaire | [Official report](https://www.statistics.gov.lk/IncomeAndExpenditure/StaticalInformation/HouseholdIncomeandExpenditureSurvey2019FinalReport) | Group |
|---------------|---------------|------------|------------|-----------|----------|
| **School attendance and dropout** | This topic has already been explored in the previous section as an example. It aims at uncovering the socio-spatial determinants of school non-attendance by age. | edu.rds | Section 2 | None | Peradeniya (5) |
| **University attainment** | Among adult respondents, who attained university education and how does it vary by age, sex and locality? | demo.rds | Section 2 | None | Ruhuna (4) |
| **Government versus private school attendance** | Among school-attending children, what are the social determinants that drive family choice for government versus private school? Are they different according to urban/rural locality and province of residence? | edu.rds | Section 2 | None | Kelaniya (5) |
| **Distance and mode of travel to school** | How is access to school, in terms of spatial distance and mode of travel, constrained by locality characteristics and social determinants? | edu.rds | Section 2 | See p.121-122-123 | Jaffna (5) |
| **Chronic illness** | Who suffers from chronic illness? Age will be an important demographic variable to examine here. | health.rds | Section 3A | See from p. 92 onwards | University of Sri Jayewardenepura, University of Colombo, Sabaragamuwa University of Sri Lanka (6) |
| **Use of health facility as an outpatient** | How does the use of private versus government health facilities as an outpatient vary by locality and social characteristics? | health.rds | Section 3A | See from p. 92 onwards | DCS (group1) |
| **Use of health facility as an inpatient** | How does the use of private versus government health facilities as an inpatient vary by locality and social characteristics? | health.rds | Section 3A | See from p. 92 onwards | \- |
| **Access to primary facilities** | How is the access to basic facilities shaped by locality of residence? | environment.rds | Section 7 | None | DCS+SEUSL (7) |
| **Water services** | How is the access to drinking water shaped by socio-spatial determinants? | environment.rds | Section 8 | None | Eastern University |
| **Sanitation and toilet availability** | Do all households get access to toilets in their premises? | environment.rds | Section 8 | None |  Rajarata University (5) |
| **Energy & electricity** | Do all households get access electricity supply and what king of energy source is used for cooking? | environment.rds | Section 7 & 8 | None | \- |
| **Garbage** | What kind of garbage facility is there for households depending on their location? | environment.rds | Section 7 & 8 | None | \- |
| *... Feel free to suggest other topics (and check it with us!)* |  |  |  |  |  |

: Topics to study in the SoMix project

HIES 2019 questionnaire:

<div>

<iframe width="100%" height="700" src="documents/HIES_2019_questionnaire.pdf">

</iframe>

</div>
